### ISSUE TITLE
[Request] Docker Installation instructions

### ISSUE THREAD

**Issue by AlexBaranowski** [EuroLinux/eurolinux-open-docs#31]
**Enterprise Linux/EuroLinux versions**

- [x] 8
- [x] 7

We already have like 5 support cases, where ppl installed RHEL instead of CentOS repo.

@tompods please remember to create task to count time

**Comment by tompods** [comment]
https://github.com/EuroLinux/eurolinux-open-docs/blob/docker/docs/HowTo/docker.md

EL7 will be covered later.

**Comment by tompods** [comment]
https://github.com/EuroLinux/eurolinux-open-docs/pull/32
