### ISSUE TITLE
[Request] create ISO from local repository

### ISSUE THREAD

**Issue by anakolutka** [EuroLinux/eurolinux-open-docs#4]
Hi,

I would like to use [fbi repo](https://fbi.cdn.euro-linux.com/dist/eurolinux/server/7/x86_64/fbi/) in my local infrastructure as an ISO to provision my VMs. 

It would be very helpful for me, if you could provide tutorial on how to create an ISO. 

**Enterprise Linux/EuroLinux versions**

- [*] 7

**Comment by AlexBaranowski** [comment]
Hi!

First of all thanks for the feedback. I will plan this work with team and return to you as soon as we will be able to decide when we are going to include it.

**Comment by AlexBaranowski** [comment]
Hi!

Once more thanks for feedback.

We decided that this kind of documentation should be done ASAP. It will be available after weekend. I will link proper PR to this issue.

**Comment by AlexBaranowski** [comment]
I linked pull-request that has how-to that you were interested in.

Best,
Alex
